config/routes.rb
Rails.application.routes.draw do
  
 resources :users 
 root 'static_pages#home' 


	get '/about' => "static_pages#about"
	get '/help' => "static_pages#help", as: 'helf'  
	get '/contact' => "static_pages#contact"
	get '/signup' => "users#new"
post '/signup', to: 'users#create'

  get 'static_pages/home'
  get 'static_pages/help'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	# validates_presence_of :name
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum:50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255}, 
	    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
	    has_secure_password 
 validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   
   def hello 
   	 render html: "hello, world!!"
	 end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end 

  def help 
  end

  def about 
  	@name = 'prativa'
  end 

  def contact 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show 
  	@user = User.find(params[:id])
  	# debugger	
  end 

	def new 
		@user = User.new

	end 

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		# Handle a successful save.
		else
			ender 'new'
		end
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end 

end 

app/helpers/example_user.rb
class User
  attr_accessor :name, :email

  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
  end

  def formatted_email
    "#{@name} <#{@email}>"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
def gravatar_for(user, options = { size: 80 })
gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
size = options[:size]
gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#(size)"
image_tag(gravatar_url, alt: user.name, class: "gravatar")
end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
 the <a href="http://www.railstutorials.org/">Ruby on Rails Tutorial</a>
 by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
 </small>
 <nav>
   <ul>
     <li><%= link_to "About",  about_url %></li>
     <li><%= link_to "Contact", contact_url %></li>
     <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
 </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  	<div class='container'>
        <%= link_to "sample app", root_url , id: "logo", :class =>'header-color'%>
        <nav>
        	<ul class="nav navbar-nav navbar-right">
        	<li><%=link_to "Home", root_url %></li>
        	<li><%=link_to "Help", helf_url %></li>
        	<li><%=link_to "Log in", '#' %></li>
        	</ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
  
    <div class="container">

    <% flash.each do |message_type, message| %>
<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
       <%= yield %>
    	 <%= render partial: 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@user.errors.count, "error") %>.
</div>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
 	<%= "This is my about page #{@name}" %>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h2>Help</h2>
<p>  
  Get help on the Ruby on Rails Tutorial at the 
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>
  To get help on this sample app,see the 
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>
  </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>welcome to the Sample App</h1>

	<h2>
	  This is the home page for the 
	  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	   sample application
	</h2>

 	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "image"),
								'http://rubyonrails.org/' %>

<!--  <%= link_to image_tag("kitten.jpg", alt: "Rails logo"),
								'http://rubyonrails.org/' %> -->

app/views/static_pages/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up </h1>

<div class = "row">
 <div class = "col-md-6 col-md-offset-3" > 
   <%= form_for (@user) do |f| %> 
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :email %>
   <%= f.text_field :email %> 

   <%= f.label :password %> 
   <%= f.password_field :password %>
   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation %>
   <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up </h1>

<div class = "row">
 <div class = "col-md-6 col-md-offset-3" > 
  <%= form_for(@user, url: signup_path) do |f| %>
   <%= render 'shared/error_messages' %>
   
   <%= f.label :name %>
   <%= f.text_field :name, class: 'form-control' %>

   <%= f.label :email %>
   <%= f.email_field :email, class: 'form-control' %>

   <%= f.label :password %> 
    <%= f.password_field :password, class: 'form-control' %>

   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation, class: 'form-control' %>
   
   <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
     <section class="user_info">
       <h1>
         <%= gravatar_for @user %>
          <%= @user.name %>
       </h1>
     </section>
    	</aside>
</div>